"""LLM-based answer judge for ChemEvoRAG.

Evaluates system answer against ground truth using a second LLM call.
Extracted from eval_questions.py for independent reuse.

Supports:
  - Default env-var based config (API_KEY, BASE_URL, LLM_MODEL)
  - Explicit api_key/base_url/model override for A/B comparison experiments
"""

from __future__ import annotations

import json
import os
from typing import Any

# ── Default judge prompt ──────────────────────────────────────────────────

JUDGE_PROMPT = """\
You are an evaluator. Compare the system's answer to the ground-truth answer.
Score from 0 to 1:
  1.0 = system answer is fully correct, contains all key facts from ground truth
  0.7 = mostly correct, minor omissions or imprecise wording
  0.5 = partially correct, some right facts but missing important details
  0.3 = vaguely related but factually wrong or very incomplete
  0.0 = completely wrong or unrelated

Also note whether key_entities from the ground truth appear in the system answer.

Return ONLY a JSON object:
{
  "score": 0.0,
  "key_entities_found": ["entity1"],
  "key_entities_missing": ["entity2"],
  "reasoning": "<one sentence explaining the score>"
}"""


# ── Public API ─────────────────────────────────────────────────────────────

def judge_answer(
    system_answer: str,
    ground_truth: str,
    key_entities: list[str] | None = None,
    *,
    api_key: str | None = None,
    base_url: str | None = None,
    model: str | None = None,
    max_tokens: int | None = None,
    judge_prompt: str | None = None,
) -> dict[str, Any]:
    """Judge a system answer against ground truth using an LLM.

    Args:
        system_answer: The answer generated by the system.
        ground_truth: The expected correct answer.
        key_entities: Optional list of key entities that SHOULD appear in the answer.
        api_key: API key. Default: os.environ["API_KEY"].
        base_url: API base URL. Default: os.environ["BASE_URL"].
        model: Model name. Default: os.environ["LLM_MODEL"] or "gpt-4o-mini".
        max_tokens: Max tokens for response. Default: os.environ["LLM_MAX_TOKENS"] or 16384.
        judge_prompt: Custom judge system prompt. Default: built-in JUDGE_PROMPT.

    Returns:
        {"score": float, "key_entities_found": [...], "key_entities_missing": [...], "reasoning": str}
    """
    entities = key_entities or []

    # Resolve credentials: explicit args > env vars
    resolved_key = api_key or os.environ.get("API_KEY")
    resolved_url = base_url or os.environ.get("BASE_URL")
    resolved_model = model or os.environ.get("LLM_MODEL", "gpt-4o-mini")
    resolved_max_tokens = max_tokens or int(os.environ.get("LLM_MAX_TOKENS", "16384"))

    if not resolved_key:
        return {
            "score": 0.0,
            "key_entities_found": [],
            "key_entities_missing": entities,
            "reasoning": "no API key configured",
        }

    try:
        from openai import OpenAI
    except ImportError:
        return {
            "score": 0.0,
            "key_entities_found": [],
            "key_entities_missing": entities,
            "reasoning": "openai not installed",
        }

    client = OpenAI(api_key=resolved_key, base_url=resolved_url or None)

    entities_str = ", ".join(entities) if entities else "none"
    user_prompt = (
        f"SYSTEM ANSWER:\n{system_answer}\n\n"
        f"GROUND TRUTH:\n{ground_truth}\n\n"
        f"KEY ENTITIES TO CHECK: [{entities_str}]"
    )

    system_prompt = judge_prompt or JUDGE_PROMPT

    try:
        r = client.chat.completions.create(
            model=resolved_model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            temperature=0.1,
            seed=42,
            max_tokens=resolved_max_tokens,
            extra_body={},
        )
        raw = r.choices[0].message.content.strip()
        # Strip markdown code fences if present
        if raw.startswith("```"):
            raw = raw.split("```")[1]
            if raw.startswith("json"):
                raw = raw[4:]
            raw = raw.strip()
        return json.loads(raw)
    except Exception as exc:
        return {
            "score": 0.0,
            "key_entities_found": [],
            "key_entities_missing": entities,
            "reasoning": str(exc),
        }


def judge_batch(
    items: list[dict[str, Any]],
    *,
    answer_field: str = "system_answer",
    truth_field: str = "ground_truth",
    entities_field: str = "key_entities",
    **judge_kwargs,
) -> list[dict[str, Any]]:
    """Judge a batch of answers. Each item must have system_answer, ground_truth, key_entities.

    Args:
        items: List of dicts with answer/truth/entities.
        answer_field: Key for system answer in each item.
        truth_field: Key for ground truth in each item.
        entities_field: Key for key entities in each item.
        **judge_kwargs: Passed to judge_answer (api_key, base_url, model, etc.).

    Returns:
        Original items extended with "judge_score", "entities_found",
        "entities_missing", "judge_reasoning".
    """
    results = []
    for item in items:
        result = judge_answer(
            system_answer=item[answer_field],
            ground_truth=item[truth_field],
            key_entities=item.get(entities_field, []),
            **judge_kwargs,
        )
        item_out = dict(item)
        item_out["judge_score"] = result["score"]
        item_out["score"] = result["score"]
        item_out["entities_found"] = result.get("key_entities_found", [])
        item_out["entities_missing"] = result.get("key_entities_missing", [])
        item_out["judge_reasoning"] = result.get("reasoning", "")
        results.append(item_out)
    return results
